export const API = "https://api.weatherapi.com/v1/forecast.json?key=9a179446b6644d8ea15170701230604&q= argentina buenos aires&days=10&aqi=no&alerts=no"
export const posibilidades = ["Patchy rain possible", "Clear", "Partly cloudy", "Cloudy", "Mist", "Overcast", "Sunny", "Light rain shower", "Heavy rain", "Moderate rain", "Fog", "Moderate or heavy rain shower", "Patchy light drizzle", "Light rain shower"]
export var dias = ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'];

export const translate: any = {
  "Sunny": "Soleado",
  "Partly cloudy": "Parcialmente nublado",
  "Cloudy": "Nublado",
  "Overcast": "Nublado",
  "Mist": "Neblina",
  "Patchy rain possible": "Es posible que llueva irregularmente",
  "Patchy snow possible": "Es posible que haya nieve irregular",
  "Patchy sleet possible": "Es posible que haya aguanieve irregular",
  "Patchy freezing drizzle possible": "Es posible una llovizna helada irregular",
  "Thundery outbreaks possible": "Posibles estallidos de tormentas",
  "Blowing snow": "La nieve que sopla",
  "Blizzard": "Tormenta de nieve",
  "Fog": "Niebla",
  "Freezing fog": "Niebla helada",
  "Patchy light drizzle": "Llovizna ligera irregular",
  "Light drizzle": "Llovizna ligera",
  "Freezing drizzle": "Llovizna helada",
  "Heavy freezing drizzle": "Llovizna intensa y helada",
  "Patchy light rain": "Lluvia ligera irregular",
  "Light rain": "Lluvia ligera",
  "Moderate rain at times": "Lluvias moderadas en ocasiones",
  "Moderate rain": "Lluvia moderada",
  "Heavy rain at times": "A veces hay fuertes lluvias",
  "Heavy rain": "Lluvia Pesada",
  "Light freezing rain": "Lluvia ligera y helada",
  "Moderate or heavy freezing rain": "Lluvia helada moderada o intensa",
  "Light sleet": "Aguanieve ligera",
  "Moderate or heavy sleet": "Aguanieve moderada o intensa",
  "Patchy light snow": "Nieve ligera irregular",
  "Light snow": "Nieve ligera",
  "Patchy moderate snow": "Nieve moderada en forma irregular",
  "Moderate snow": "Nieve moderada",
  "Patchy heavy snow": "Nieve intensa e irregular",
  "Heavy snow": "Fuertes nevadas",
  "Ice pellets": "Gránulos de hielo",
  "Light rain shower": "Lluvia ligera",
  "Moderate or heavy rain shower": "Lluvias moderadas o fuertes",
  "Torrential rain shower": "Lluvia torrencial",
  "Light sleet showers": "Lluvias ligeras de aguanieve",
  "Moderate or heavy sleet showers": "Lluvias de aguanieve moderadas o intensas",
  "Light snow showers": "Duchas de nieve liviana",
  "Moderate or heavy snow showers": "Nieves moderadas o fuertes",
  "Light showers of ice pellets": "Lluvias ligeras de bolitas de hielo",
  "Moderate or heavy showers of ice pellets": "Lluvias moderadas o fuertes de granulado de hielo",
  "Patchy light rain with thunder": "Lluvia ligera irregular con truenos",
  "Moderate or heavy rain with thunder": "Lluvias moderadas o fuertes con truenos",
  "Patchy light snow with thunder": "Nieve ligera e irregular con truenos",
  "Moderate or heavy snow with thunder": "Nieve moderada o intensa con truenos"
}

export const icons: any = {
  "Patchy rain possible": "cloud-rain",
  "Clear": "brightness-high",
  "Clear night": "moon",
  "Partly cloudy": "cloud-sun",
  "Partly cloudy night": "cloud-moon",
  "Cloudy": "clouds",
  "Mist": "cloud-snow",
  "Overcast": "clouds",
  "Sunny": "brightness-high",
  "Sunny night": "moon",
  "Light rain shower": "cloud-rain",
  "Heavy rain": "cloud-rain-heavy",
  "Moderate rain": "cloud-rain",
  "Fog": "cloud-snow",
  "Moderate or heavy rain shower": "cloud-rain",
  "Patchy light drizzle": "cloud-drizzle",
  "Patchy light snow": "snow",
  "Patchy snow possible": "cloud-snow",
  "Moderate snow": "cloud-snow",
  "Heavy snow": "snow",
  "Patchy heavy snow": "snow",
  "Light sleet": "cloud-sleet",
  "Freezing fog": "cloud-snow",
  "Light snow": "snow",
  "Patchy moderate snow": "snow",
  "Moderate or heavy snow showers": "cloud-rain-heavy",
  "Patchy sleet possible": "cloud-sleet",
  "Patchy freezing drizzle possible": "cloud-drizzle",
  "Thundery outbreaks possible": "cloud-lightning",
  "Blowing snow": "wind",
  "Blizzard": "cloud-snow",
  "Light drizzle": "cloud-drizzle",
  "Freezing drizzle": "cloud-drizzle",
  "Heavy freezing drizzle": "cloud-drizzle",
  "Patchy light rain": "cloud-drizzle",
  "Light rain": "cloud-drizzle",
  "Moderate rain at times": "cloud-drizzle",
  "Heavy rain at times": "cloud-rain-heavy",
  "Light freezing rain": "cloud-drizzle",
  "Moderate or heavy freezing rain": "cloud-rain-heavy",
  "Moderate or heavy sleet": "cloud-sleet",
  "Ice pellets": "snow3",
  "Torrential rain shower": "cloud-lightning-rain",
  "Light sleet showers": "cloud-sleet",
  "Moderate or heavy sleet showers": "cloud-sleet",
  "Light snow showers": "cloud-snow",
  "Light showers of ice pellets": "cloud-snow",
  "Moderate or heavy showers of ice pellets": "cloud-snow",
  "Patchy light rain with thunder": "cloud-lightning-rain",
  "Moderate or heavy rain with thunder": "cloud-lightning-rain",
  "Patchy light snow with thunder": "snow2",
  "Moderate or heavy snow with thunder": "snow2"
}

export const background: any = {
  "dia": {
    "Patchy rain possible": "dia-nublado.jpg",
    "Clear": "dia-soleado.jpg",
    "Partly cloudy": "dia-parcialmente-nublado.jpg",
    "Cloudy": "dia-nublado.jpg",
    "Mist": "dia-soleado-niebla.png",
    "Overcast": "dia-nublado.jpg",
    "Sunny": "dia-soleado.jpg",
    "Light rain shower": "dia-lluviozo.jpg",
    "Heavy rain": "dia-lluviozo.jpg",
    "Moderate rain": "dia-lluviozo.jpg",
    "Fog": "dia-soleado-niebla.png",
    "Moderate or heavy rain shower": "dia-lluviozo.jpg",
    "Patchy light drizzle": "dia-lluviozo.jpg",
    "Heavy snow": "dia-nieve.jpg",
    "Patchy heavy snow": "dia-nieve.jpg",
    "Light sleet": "dia-lluviozo.jpg",
    "Freezing fog": "dia-nieve-helada.jpg",
    "Light snow": "dia-nieve-helada.jpg",
    "Patchy moderate snow": "dia-nieve-helada.jpg",
    "Moderate or heavy snow showers": "dia-nieve-helada.jpg",
    "Patchy snow possible": "dia-nieve-helada.jpg",
    "Patchy sleet possible": "dia-nieve-helada.jpg",
    "Patchy freezing drizzle possible": "dia-nieve-helada.jpg",
    "Thundery outbreaks possible": "dia-lluviozo.jpg",
    "Blowing snow": "dia-nieve.jpg",
    "Blizzard": "dia-nieve-helada.jpg",
    "Light drizzle": "dia-nublado.jpg",
    "Freezing drizzle": "dia-nieve-helada.jpg",
    "Heavy freezing drizzle": "dia-nieve-helada.jpg",
    "Patchy light rain": "dia-lluviozo.jpg",
    "Light rain": "dia-lluviozo.jpg",
    "Moderate rain at times": "dia-lluviozo.jpg",
    "Heavy rain at times": "dia-lluviozo.jpg",
    "Light freezing rain": "dia-lluviozo.jpg",
    "Moderate or heavy freezing rain": "dia-nieve-helada.jpg",
    "Moderate or heavy sleet": "dia-nieve-helada.jpg",
    "Patchy light snow": "dia-nieve.jpg",
    "Moderate snow": "dia-nieve.jpg",
    "Ice pellets": "dia-nieve-helada.jpg",
    "Torrential rain shower": "Lluvia torrencial",
    "Light sleet showers": "dia-lluviozo.jpg",
    "Moderate or heavy sleet showers": "dia-lluviozo.jpg",
    "Light snow showers": "dia-nieve.jpg",
    "Light showers of ice pellets": "dia-nieve-helada.jpg",
    "Moderate or heavy showers of ice pellets": "dia-nieve-helada.jpg",
    "Patchy light rain with thunder": "dia-nieve-helada.jpg",
    "Moderate or heavy rain with thunder": "dia-nieve.jpg",
    "Patchy light snow with thunder": "dia-nieve-helada.jpg",
    "Moderate or heavy snow with thunder": "dia-nieve-helada.jpg"
  },
  "noche": {
    "Patchy rain possible": "noche-tormenta.jpg",
    "Clear": "noche-clara.jpg",
    "Partly cloudy": "noche-nublado.jpg",
    "Cloudy": "noche-nublado.jpg",
    "Mist": "noche-clara-niebla.png",
    "Overcast": "noche-nublado.jpg",
    "Sunny": "noche-clara.jpg",
    "Light rain shower": "noche-lluvia.jpg",
    "Heavy rain": "noche-tormenta.jpg",
    "Moderate rain": "noche-lluvia.jpg",
    "Moderate snow": "noche-nieve.png",
    "Fog": "noche-clara-niebla.png",
    "Moderate or heavy rain shower": "noche-lluvia.jpg",
    "Patchy light drizzle": "noche-lluvia.jpg",
    "Heavy snow": "noche-nieve.png",
    "Patchy heavy snow": "noche-nieve.png",
    "Light sleet": "noche-lluvia.jpg",
    "Freezing fog": "noche-nublado-niebla.jpg",
    "Light snow": "noche-nieve.png",
    "Patchy moderate snow": "noche-nieve.png",
    "Moderate or heavy snow showers": "noche-nieve.png",
    "Patchy snow possible": "noche-nieve.png",
    "Patchy sleet possible": "noche-lluvia.jpg",
    "Patchy freezing drizzle possible": "noche-lluvia.jpg",
    "Thundery outbreaks possible": "noche-tormenta.jpg",
    "Blowing snow": "noche-nieve.png",
    "Blizzard": "noche-nieve.png",
    "Light drizzle": "noche-lluvia.jpg",
    "Freezing drizzle": "noche-lluvia.jpg",
    "Heavy freezing drizzle": "noche-lluvia.jpg",
    "Patchy light rain": "noche-lluvia.jpg",
    "Light rain": "noche-lluvia.jpg",
    "Moderate rain at times": "noche-lluvia.jpg",
    "Heavy rain at times": "noche-tormenta.jpg",
    "Light freezing rain": "noche-lluvia.jpg",
    "Moderate or heavy freezing rain": "noche-lluvia.jpg",
    "Moderate or heavy sleet": "noche-lluvia.jpg",
    "Patchy light snow": "noche-nieve.png",
    "Ice pellets": "noche-nieve.png",
    "Torrential rain shower": "noche-lluvia.jpg",
    "Light sleet showers": "noche-lluvia.jpg",
    "Moderate or heavy sleet showers": "noche-tormenta.jpg",
    "Light snow showers": "noche-nieve.png",
    "Light showers of ice pellets": "noche-lluvia.jpg",
    "Moderate or heavy showers of ice pellets": "noche-lluvia.jpg",
    "Patchy light rain with thunder": "noche-tormenta.jpg",
    "Moderate or heavy rain with thunder": "noche-tormenta.jpg",
    "Patchy light snow with thunder": "noche-nieve.png",
    "Moderate or heavy snow with thunder": "Nnoche-nieve.png"
  },

  "atardecer": {
    "Patchy rain possible": "dia-nublado.jpg",
    "Clear": "atardecer-claro.jpg",
    "Partly cloudy": "atardecer-nublado.jpg",
    "Cloudy": "atardecer-nublado.jpg",
    "Mist": "noche-clara-niebla.png",
    "Overcast": "atardecer-nublado.jpg",
    "Sunny": "atardecer-claro.jpg",
    "Light rain shower": "noche-lluvia.jpg",
    "Heavy rain": "noche-lluvia.jpg",
    "Moderate rain": "noche-lluvia.jpg",
    "Fog": "noche-clara-niebla.png",
    "Moderate or heavy rain shower": "noche-lluvia.jpg",
    "Patchy light drizzle": "noche-lluvia.jpg",
    "Heavy snow": "noche-nieve.png",
    "Patchy heavy snow": "noche-nieve.png",
    "Light sleet": "noche-lluvia.jpg",
    "Freezing fog": "noche-clara-niebla.png",
    "Light snow": "noche-nieve.png",
    "Patchy moderate snow": "noche-nieve.png",
    "Moderate or heavy snow showers": "noche-nieve.png",
    "Patchy snow possible": "noche-nieve.png",
    "Patchy sleet possible": "noche-lluvia.jpg",
    "Patchy freezing drizzle possible": "noche-lluvia.jpg",
    "Thundery outbreaks possible": "noche-tormenta.jpg",
    "Blowing snow": "noche-nieve.png",
    "Blizzard": "noche-nieve.png",
    "Light drizzle": "noche-lluvia.jpg",
    "Freezing drizzle": "noche-lluvia.jpg",
    "Heavy freezing drizzle": "noche-lluvia.jpg",
    "Patchy light rain": "noche-lluvia.jpg",
    "Light rain": "noche-lluvia.jpg",
    "Moderate rain at times": "noche-lluvia.jpg",
    "Heavy rain at times": "noche-tormenta.jpg",
    "Light freezing rain": "noche-lluvia.jpg",
    "Moderate or heavy freezing rain": "noche-lluvia.jpg",
    "Moderate or heavy sleet": "noche-lluvia.jpg",
    "Patchy light snow": "noche-nieve.png",
    "Ice pellets": "noche-nieve.png",
    "Torrential rain shower": "noche-lluvia.jpg",
    "Light sleet showers": "noche-lluvia.jpg",
    "Moderate or heavy sleet showers": "noche-tormenta.jpg",
    "Light snow showers": "noche-nieve.png",
    "Light showers of ice pellets": "noche-lluvia.jpg",
    "Moderate or heavy showers of ice pellets": "noche-lluvia.jpg",
    "Patchy light rain with thunder": "noche-tormenta.jpg",
    "Moderate or heavy rain with thunder": "noche-tormenta.jpg",
    "Patchy light snow with thunder": "noche-nieve.png",
    "Moderate or heavy snow with thunder": "Nnoche-nieve.png"
  },

  "amanecer": {
    "Patchy rain possible": "dia-nublado.jpg",
    "Clear": "atardecer-claro.jpg",
    "Partly cloudy": "atardecer-nublado.jpg",
    "Cloudy": "atardecer-nublado.jpg",
    "Mist": "dia-soleado-niebla.png",
    "Overcast": "atardecer-nublado.jpg",
    "Sunny": "atardecer-claro.jpg",
    "Light rain shower": "dia-lluviozo.jpg",
    "Heavy rain": "dia-lluviozo.jpg",
    "Moderate rain": "dia-lluviozo.jpg",
    "Fog": "dia-soleado-niebla.png",
    "Moderate or heavy rain shower": "dia-lluviozo.jpg",
    "Patchy light drizzle": "dia-lluviozo.jpg",
    "Heavy snow": "dia-nieve.jpg",
    "Patchy heavy snow": "dia-nieve.jpg",
    "Light sleet": "dia-lluviozo.jpg",
    "Freezing fog": "dia-nieve-helada.jpg",
    "Light snow": "dia-nieve-helada.jpg",
    "Patchy moderate snow": "dia-nieve-helada.jpg",
    "Moderate or heavy snow showers": "dia-nieve-helada.jpg",
    "Patchy snow possible": "dia-nieve-helada.jpg",
    "Patchy sleet possible": "dia-nieve-helada.jpg",
    "Patchy freezing drizzle possible": "dia-nieve-helada.jpg",
    "Thundery outbreaks possible": "dia-lluviozo.jpg",
    "Blowing snow": "dia-nieve.jpg",
    "Blizzard": "dia-nieve-helada.jpg",
    "Light drizzle": "dia-nublado.jpg",
    "Freezing drizzle": "dia-nieve-helada.jpg",
    "Heavy freezing drizzle": "dia-nieve-helada.jpg",
    "Patchy light rain": "dia-lluviozo.jpg",
    "Light rain": "dia-lluviozo.jpg",
    "Moderate rain at times": "dia-lluviozo.jpg",
    "Heavy rain at times": "dia-lluviozo.jpg",
    "Light freezing rain": "dia-lluviozo.jpg",
    "Moderate or heavy freezing rain": "dia-nieve-helada.jpg",
    "Moderate or heavy sleet": "dia-nieve-helada.jpg",
    "Patchy light snow": "dia-nieve.jpg",
    "Moderate snow": "dia-nieve.jpg",
    "Ice pellets": "dia-nieve-helada.jpg",
    "Torrential rain shower": "Lluvia torrencial",
    "Light sleet showers": "dia-lluviozo.jpg",
    "Moderate or heavy sleet showers": "dia-lluviozo.jpg",
    "Light snow showers": "dia-nieve.jpg",
    "Light showers of ice pellets": "dia-nieve-helada.jpg",
    "Moderate or heavy showers of ice pellets": "dia-nieve-helada.jpg",
    "Patchy light rain with thunder": "dia-nieve-helada.jpg",
    "Moderate or heavy rain with thunder": "dia-nieve.jpg",
    "Patchy light snow with thunder": "dia-nieve-helada.jpg",
    "Moderate or heavy snow with thunder": "dia-nieve-helada.jpg"
  }
}
